In [1]:
import numpy as np
import pandas as pd
import os
import string

In [2]:
dataset = pd.read_csv("plant_village.csv")

In [3]:
dataset.head(30)

Unnamed: 0      mean_r      mean_g      mean_b   stddev_r   stddev_g  \
0            0  124.451584  125.620300  108.485748  50.388144  41.485965   
1            0   99.800812  106.241577   95.636383  53.178032  46.293921   
2            0  128.854691  133.116470  125.494598  51.777342  43.455868   
3            0  118.155594  129.549210   96.848831  51.552275  47.672393   
4            0   94.497757  103.165131   79.188477  58.576800  51.213358   
5            0  110.709595  120.171036   93.429062  47.789392  30.175715   
6            0  104.086609  111.648010   90.517944  58.891686  56.248688   
7            0  135.240723  131.895370   94.359283  44.033809  37.311923   
8            0  101.134720  108.501678   88.009781  59.171141  50.670311   
9            0  115.889175  124.028458  105.472321  61.010069  46.588491   
10           0  147.559372  155.865723  133.580460  53.430600  36.244772   
11           0  112.725250  111.658569   88.138382  57.864767  46.829607   
12           0  118.543518  120.566757  102.514618  53.821701  43.525105   
13           0  131.529617  135.393906   95.408127  43.880363  37.311436   
14           0  134.426193  138.307007  100.986710  38.974747  36.228678   
15           0  100.085342   99.324814   75.211395  63.735467  58.374294   
16           0  125.873962  137.114105  114.387222  44.660921  41.081717   
17           0  122.173950  130.118546  104.384644  50.938494  42.958840   
18           0  106.584427  114.636734   93.545181  56.720479  50.171987   
19           0  132.006638  126.564377  105.034592  59.795148  51.406370   
20           0  112.691971  118.842407  110.944382  49.435703  42.776874   
21           0  101.081497  106.779800   85.806305  57.734974  55.344931   
22           0  108.028366  107.008774   82.302109  61.306011  53.745461   
23           0  111.466644  109.306152   80.060287  61.119749  52.899950   
24           0  149.647675  152.457428  105.463821  41.814630  28.104465   
25           0  111.502502  114.450119   90.802765  58.481047  46.553614   
26           0  112.460480  105.512375   81.785736  61.187051  54.876784   
27           0  109.264954  110.884979   84.727859  56.331608  47.725776   
28           0  118.565079  123.240387  109.720871  54.999136  44.846738   
29           0  133.479996  140.212311   96.851181  51.807307  50.769087   

     stddev_b     contrast  correlation  inverse_difference_moments    entropy  
0   53.374898   544.214069     0.862938                    0.097321  13.205401  
1   56.707237  1024.899346     0.780989                    0.100739  13.721206  
2   56.003065   668.621700     0.846056                    0.098733  13.512516  
3   56.637736  1826.944441     0.590644                    0.039873  14.459833  
4   59.374794   792.271595     0.860727                    0.114316  13.517625  
5   48.727497   359.498229     0.866027                    0.090358  12.816389  
6   58.665713   728.959001     0.885723                    0.154391  13.090009  
7   53.750357   467.791379     0.847512                    0.115724  12.797442  
8   61.012097   783.534399     0.863051                    0.104254  13.554903  
9   62.228476   612.859330     0.886738                    0.097306  13.290813  
10  55.232799   536.457131     0.854064                    0.073798  13.187859  
11  52.593662   840.815166     0.832955                    0.074135  13.833883  
12  54.416560   417.077719     0.905742                    0.123465  12.861741  
13  54.213508   404.504964     0.866682                    0.119212  12.784327  
14  64.173187   112.740211     0.958215                    0.305494  11.129659  
15  59.809017   807.605897     0.885359                    0.131795  13.398646  
16  46.313852   805.195682     0.748903                    0.064758  13.603044  
17  66.764345   540.259646     0.870574                    0.129885  13.244241  
18  60.100497   714.829395     0.869940                    0.097192  13.688498  
19  58.358060   721.503055 

In [4]:
type(dataset)

pandas.core.frame.DataFrame

In [9]:
maindir = r'C:\Users\Acer\Desktop\Leaf-Disease-Detection-Using-Image-Processing-main\Leaf-Disease-Detection-Using-Image-Processing-main'
ds_path = maindir + "\\crowdai"
img_files = os.listdir(ds_path)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Acer\\Desktop\\Leaf-Disease-Detection-Using-Image-Processing-main\\Leaf-Disease-Detection-Using-Image-Processing-main\\crowdai'

In [6]:
img_files[0]

'Pepper__bell___Bacterial_spot'

In [7]:
breakpoints = [1000,1269,1270,1549,1550,1673,1674,2386,2387,2972,2973,3482,3483,3840,3841,4031,4032,4550,4551,4924,4925,5369,5370,5845,5846,6397,6398,6817,6818,6988,6989,9309,9310,9999]
print(len(breakpoints))

34


In [8]:
target_list = []
for file in img_files:
    target_num = int(file.split(".")[0])
   # print(target_num)
    flag = 0
    i = 0 
    for i in range(0,len(breakpoints),2):
        if((target_num >= breakpoints[i]) and (target_num <= breakpoints[i+1])):
            flag = 1
            break
    
    if(flag==1):
        target = int((i/2))
        target_list.append(target)

ValueError: invalid literal for int() with base 10: 'Pepper__bell___Bacterial_spot'

In [35]:
y = np.array(target_list)
y

array([], dtype=float64)

In [36]:

X = dataset.iloc[:,1:]

In [37]:
X.head(5)

mean_r      mean_g      mean_b   stddev_r   stddev_g   stddev_b  \
0  124.451584  125.620300  108.485748  50.388144  41.485965  53.374898   
1   99.800812  106.241577   95.636383  53.178032  46.293921  56.707237   
2  128.854691  133.116470  125.494598  51.777342  43.455868  56.003065   
3  118.155594  129.549210   96.848831  51.552275  47.672393  56.637736   
4   94.497757  103.165131   79.188477  58.576800  51.213358  59.374794   

      contrast  correlation  inverse_difference_moments    entropy  
0   544.214069     0.862938                    0.097321  13.205401  
1  1024.899346     0.780989                    0.100739  13.721206  
2   668.621700     0.846056                    0.098733  13.512516  
3  1826.944441     0.590644                    0.039873  14.459833  
4   792.271595     0.860727                    0.114316  13.517625

In [38]:
y[0:5]

array([], dtype=float64)

In [39]:
#Train test split

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 142)

ValueError: Found input variables with inconsistent numbers of samples: [997, 0]

In [19]:
X_train.head(5)

mean_r      mean_g      mean_b   stddev_r   stddev_g   stddev_b  \
3964  110.072104  159.233719  131.961972  27.140586  24.466712  27.389126   
1067   82.564043   98.890889  109.420928  39.298992  38.468545  51.228020   
2401  115.825688  118.737737   94.857721  38.179354  36.353173  44.758595   
4766  104.578959  118.873818   90.257840  68.741033  52.769674  68.411842   
101   139.361927  145.180421  137.465901  65.475447  61.570231  69.279968   

        contrast  correlation  inverse_difference_moments    entropy  
3964   95.133817     0.925400                    0.178761  11.490641  
1067  164.482505     0.947380                    0.155684  12.454126  
2401   57.467823     0.978724                    0.289971  11.277982  
4766  566.730354     0.917908                    0.083414  13.676810  
101   817.508787     0.893893                    0.130472  13.343331

In [20]:
X_train.shape

(6299, 10)

In [21]:
y_train[0:5]

array([10,  3,  5, 11,  0])

In [22]:
#Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [25]:
X_train[0:2]

array([[-0.27135619,  1.72574766,  1.297164  , -1.25987687, -1.07737475,
        -1.74538858, -0.81620459,  0.21267105, -0.11418883, -0.47311907],
       [-1.58551432, -1.06029926,  0.44147284, -0.37957632,  0.01614473,
         0.1912474 , -0.56039989,  0.57567253, -0.32973539,  0.25786502]])

In [26]:
y_train[0:2]

array([10,  3])

In [27]:
#Applying SVM classifier model

In [28]:
from sklearn import svm

In [29]:
clf = svm.SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
clf.fit(X_train,y_train)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
y_pred = clf.predict(X_test)

In [31]:
from sklearn import metrics

In [32]:
metrics.accuracy_score(y_test, y_pred)

0.8314814814814815

In [33]:
from sklearn.model_selection import GridSearchCV


In [36]:
parameters = [{'kernel': ['rbf'],
               'gamma': [1e-4, 1e-3, 0.01, 0.1, 0.2, 0.5],
               'C': [1, 10, 100, 1000]},
              {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}
             ]

In [37]:
svm_clf = GridSearchCV(svm.SVC(decision_function_shape='ovr'), parameters, cv=5)
svm_clf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'kernel': ['rbf'], 'gamma': [0.0001, 0.001, 0.01, 0.1, 0.2, 0.5], 'C': [1, 10, 100, 1000]}, {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [38]:
svm_clf.best_params_

{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}

In [ ]:
print(metrics.classification_report(y_test, y_pred))

In [46]:
int(int(clf.predict(X_train[0:1])))

3

In [39]:
clf = svm.SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
clf.fit(X_train,y_train)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [40]:
y_pred = clf.predict(X_test)

In [41]:
metrics.accuracy_score(y_test, y_pred)

0.8688888888888889